export const dark = {
  background: "#292a35",
  title: "rgb(100,200,100)",
  text: "white",
  semititle: "skyblue",
  toggleBarActivated: "rgb(103,205,103)",
  toggleBarUnactivated: "#767577",
  toggle: "#f4f3f4",
  pharmDataContent: "gray",
  textSize: 20,
  bigTextSize: 30,
  titleSize: 30,
  bigTitleSize: 40,
  semiTitleSize: 25,
  bigSemiTitleSize: 35,
};

export const light = {
  background: "white",
  title: "black",
  text: "black",
  semititle: "black",
  toggleBarActivated: "rgb(103,205,103)",
  toggleBarUnactivated: "#767577",
  toggle: "#f4f3f4",
  pharmDataContent: "lightgray",
  textSize: 20,
  bigTextSize: 30,
  titleSize: 30,
  bigTitleSize: 40,
  semiTitleSize: 25,
  bigSemiTitleSize: 35,
};
